spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/inventory-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 9094